#!/bin/bash
#

TAG=$(date +'%Y.%m.%d')
REGISTRY_URL="<registry-url>"

docker build -t ${REGISTRY_URL}:${TAG} .
docker tag ${REGISTRY_URL}:${TAG} ${REGISTRY_URL}:latest

docker push ${REGISTRY_URL}:${TAG}
docker push ${REGISTRY_URL}:latest
