apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xplenty

commonLabels:
  workload: sshtunnel

configMapGenerator:
- name: autossh-config
  literals:
  - CONN_PORT=
  - DB_URL=
  - DB_PORT=
  - XPLENTY_SERVER=

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- secrets.yaml
- pdb.yaml
